### ISSUE TITLE
Potential credential stealer / backdoor in MailSniper (Invoke-GlobalO365MailSearch connects to typosquatted domain ofiice365.com)

### ISSUE THREAD

**Issue by Robert-Fl** [dafthack/MailSniper#104]
In the function `Invoke-GlobalO365MailSearch` the parameter `ExchHostname` defaults to `outlook.ofiice365.com` instead of `outlook.office365.com`.

https://github.com/dafthack/MailSniper/blob/f6fd1441feb246ba0d1c6d47f7f3a6dcbe3d2b92/MailSniper.ps1#L364

`ExchHostname` is subsequently used as a target for `New-PSSession`, which performs a basic auth (`-Credential $Credtoken -Authentication Basic`) with the admin credentials. Without having researched the authentication logic of PSSession authentication, I'd assume that the owner of `ofiice365.com` is able to capture those credentials. This could be hazardous for any pentester or red teamer using MailSniper.

https://github.com/dafthack/MailSniper/blob/f6fd1441feb246ba0d1c6d47f7f3a6dcbe3d2b92/MailSniper.ps1#L504

This line was introduced in #84. The domain `ofiice365.com` currently (seems to?) serve some domain parking.

**Comment by L1ghtn1ng** [comment]
Thanks for reporting this, have fixed your line you pointed out

**Comment by e1b2i3** [comment]
Markdown

**Comment by e1b2i3** [comment]
[LICENSE.txt](https://github.com/user-attachments/files/18462847/LICENSE.txt)
