### ISSUE TITLE
Output CSV Formatting issues

### ISSUE THREAD

**Issue by dafthack** [dafthack/MailSniper#24]
The OutputCsv functionality of Invoke-GlobalMailSearch is not appending to the CSV correctly for all emails. Some are being appended correctly where there is a column for each header (Sender, ReceivedBy, Subject, Body) but some rows are not populating the columns correctly.

**Comment by elvarb** [comment]
Have issues as well but with invoke-selfsearch. Did regex search of my own mailbox and the body column includes newlines so the csv file is like this

```
#TYPE Selected.Microsoft.Exchange.WebServices.Data.EmailMessage
"Sender","ReceivedBy","Subject","Body"
"The Sender","The reiever address","Full subject","
Hi there
This is a test email

With the best tests

"
```

**Comment by elvarb** [comment]
Modifing the csv output code solves this 

```
  if ($OutputCsv -ne "")
  { 
    $PostSearchList | %{
        $_.Body = $_.Body -replace "`r`n",'\n'
    }
    $PostSearchList | Select-Object Sender,ReceivedBy,Subject,Body | Export-Csv $OutputCsv
  }
```

**Comment by dafthack** [comment]
Thanks a ton! I will try to test this out this week.

**Comment by dafthack** [comment]
Finally got around to this. Also, replaced commas with &#44;.
