### ISSUE TITLE
O365 compatibility 

### ISSUE THREAD

**Issue by brianhaugli** [dafthack/MailSniper#42]
Is this working with Exchange Online?

**Comment by dafthack** [comment]
Yes. Give Invoke-SelfSearch the -Remote flag and pass -ExchHostname outlook.office365.com. It will prompt for creds.

**Comment by ArgyleD** [comment]
Will Invoke-GlobalMailSearch work in the same way? I'm having trouble with O365

Invoke-GlobalMailSearch -ExchHostname outlook.office365.com -EmailList GAB.txt -AdminUserName (domain\memberofExchangeOrganizationAdministrators) -AdminPassword Password1 -OutputCSV here.csv

**Comment by dafthack** [comment]
Hey ArgyleD, Currently Invoke-GlobalMailSearch doesn't work with O365. One option you could possibly do to achieve the same results would be to login to the O365 Admin portal and do a compliance search as detailed in this blog post: https://msitpros.com/?p=3678.

I will look into seeing if there is anyway Invoke-GlobalSearch could do this for O365.

Hope that helps!

**Comment by ArgyleD** [comment]
Thank you, this helps! I've had great success with MailSniper on Exchange it's great for demonstrating impact to C-Levels.

**Comment by elvarb** [comment]
Has any progress been made into global mail search for O365?

**Comment by rkovaci** [comment]
is there any support for office365 for Invoke-PasswordSprayOWA by any chance?
