### ISSUE TITLE
Delete Invoke-DomainHarvestOWA and add remote PARAMETER to the Invoke-GlobalMailSearch

### ISSUE THREAD

**Issue by xuseman** [dafthack/MailSniper#51]
Domain can be get from HTTP header which is encoded by base64,Invoke-GlobalMailSearch can not be used by exchange2007_sp2

**Comment by dafthack** [comment]
Modified Invoke-DomainHarvestOWA function to get domain from HTTP header. Will try to work on getting Invoke-GlobalMailSearch working remotely.
