### ISSUE TITLE
Office 365 Regex credit card

### ISSUE THREAD

**Issue by Wipsly** [dafthack/MailSniper#57]
Hi,

I tried following command.

`Invoke-SelfSearch -Remote -ExchHostname outlook.office365.com -Regex '.*3[47][0-9]{13}.*|.*(?:5[15][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][09]{2}|27[01][0-9]|2720)[0-9]{12}.*|.*4[0-9]{12}(?:[09]{3}).*' -CheckAttachments -MailsPerUser 1000`

But it Returns nothing. Any idea? There are a lot of mails with credit Cards in my Mailbox.

It seems that it does not working. In my PowerShell It tries to connect and then Exit 

[*] Trying Exchange version Exchange2010
[*] Using EWS URL https://outlook.office365.com/EWS/Exchange.asmx

**Comment by dafthack** [comment]
Hey man, I won't be able to troubleshoot this until next week but the first thing I would mention is that the regex is looking for VISA, MasterCard, and American Express numbers. So if the cards in your mailbox aren't one of those then it won't find it. Also, are the card numbers in the body of the email or in the attachments. I see you are using the -CheckAttachments option.

**Comment by Wipsly** [comment]
Hi,
thanks for your response. The regex is not the problem. I sent myself an email with subject "Password" and also with "Password" in the Body and just tried the default settings. But I think that the Connection to EWS is not working or the session is just closing because after 

`[] Using EWS URL https://outlook.office365.com/EWS/Exchange.asmx`

Nothing happens... In your Blogpost there is a screenshot with "Now searching..." But I never see something I like that...

**Comment by dafthack** [comment]
Oh that is an odd issue. I would also assume that the connection isn't working to EWS... At that point in the script it should actually be trying to bind to the Inbox. I will check it out next week and see if I can replicate the issue.

**Comment by Wipsly** [comment]
Any updates?

**Comment by dafthack** [comment]
I just tested it and it seems to be working for me. I used the following command to search for 'password' against an O365 account and it found my test email with the term password in the body. 

```

PS C:\> Invoke-SelfSearch -ExchHostname outlook.office365.com -Terms "*password*" -Remote -Mailbox r@testdomainonO365.com

[*] Trying Exchange version Exchange2010

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
[*] Using EWS URL https://outlook.office365.com/EWS/Exchange.asmx
[***] Found folder: Inbox
[*] Now searching mailbox: r@testdomainonO365.com for the terms *password*.

Sender                                      ReceivedBy                             Subject          Body
------                                        ------                                       ------             ------
beau@blackhillsinfosec.com   r@testdomainonO365.com    Test Email   This message has a password in it...

```

If authentication was failing for you I believe you would see at least an error stating the request failed so it's probably not that. What version of PowerShell are you running and what OS? Also, can you try logging directly in to EWS with a browser at https://outlook.office365.com/EWS/Exchange.asmx? You should see the Service page after logging in there if it was successful.

**Comment by Wipsly** [comment]
Ah, I think i found the problem. I use a system with german language and german office 365. If iuse use the -folder all parameter it works. Seems it does not work because of the default folder "inbox".
