### ISSUE TITLE
Latest version: "reserved for future use" and other errors

### ISSUE THREAD

**Issue by stevebottoms** [dafthack/MailSniper#79]
Using latest release (d/l today 7/11/2019) running under Powershell 5.1 on Win10, both elevated and non-elevated; on import-module I'm seeing multiple errors such as "'<' operator reserved for future use" and "ampersand (&) character not allowed", unexpected tokens, and missing file specs after redirection.  I'm sure it's something basic with powershell, perhaps it needs 32-bit vs 64-bit?  Need an older version?  Something to modify in source file?  Suggestions would be appreciated!

Thanks!
Steve

**Comment by leebaird** [comment]
Unable to reproduce.
