### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by bhuvaneswari01** [dafthack/MailSniper#86]
I am getting the error as below . When i am using the command as "($Credential =new-object -typename System.Management.Automation.PSCredential -argumentlist @($username,$pwd) "

**Error**:"new-object : Cannot find an overload for "PSCredential" and the argument count: "2".
At line:10 char:14
+ ... Credential =new-object -typename System.Management.Automation.PSCrede ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand"

**Comment by leebaird** [comment]
There have been a couple of PRs merged today. Please re-test.

**Comment by L1ghtn1ng** [comment]
timeout
