### ISSUE TITLE
Typo: Invoke-GlobalO365MailSearch -UsePrtImperonsationAccount

### ISSUE THREAD

**Issue by shaharzelig** [dafthack/MailSniper#93]
There is a typo in the function Invoke-GlobalO365MailSearch parameter:
Imperonsation should be impersonation

Change:
UsePrtImperonsationAccount -> UsePrtImpersonationAccount

**Comment by L1ghtn1ng** [comment]
Please submit a PR for it and will be more than happy to merge it. Thanks☺️

**Comment by leebaird** [comment]
Fixed.
